workshops/tokyo-workshop-20190404/Dockerfile
workshops/tokyo-workshop-20190404/README.md

Here is the material from the Workshop in Tokyo from April 4th, 2019.

Tokyo Workshop Material

---

docs/setup/create-a-wallet.md
theme/_layouts/default.html
theme/_layouts/homepage.html

Added new sections and copy from the [beginner's guide blog post](https://blog.singularitynet.io/a-beginners-guide-to-the-singularitynet-beta-74d523902958), linked the official [MetaMask instructional video](https://www.youtube.com/watch?time_continue=6&v=ZIGUC9JAAw8) and avoided the use of MetaMask prints because this would take a lot of space and not bring much relevant information.
Closes #43

Review and improve create-a-wallet.md

---

docs/concepts/snet-cli.md
docs/contribute/contribution-guidelines.md
docs/development/mpe-example.md
docs/development/mpe-example1.md
docs/setup/call-a-service.md
docs/setup/create-a-wallet.md
docs/setup/requirements.md
tutorials/docker/Dockerfile
tutorials/process/index.md
tutorials/publish.md
tutorials/sdk.md

Fixes:
- #75 
- #76 
- #77 
- #78 
- #79 
- #80

Fixing some reported issues.

---

docs/concepts/mpe-stateless-client.md
docs/concepts/rfai.md
docs/setup/create-a-wallet.md

Implemented the text from[ RFAI's `README.md`](https://github.com/singnet/snet-rfai) as specified by Raam and tried to improve it a bit. 
_Not sure if this is a priority, but I believe that this page should have someone from the marketing team to elaborate on the copy._
Navigation
- Previous: MPE Stateless Client
- Next: Back to Concepts
Closes #50

Add and populate rfai.md

---

docs/concepts/daemon.md
docs/concepts/index.md
docs/concepts/organization-metadata.md
docs/concepts/organization.md
docs/concepts/service.md
tutorials/go/template/daemonConfigFile.template.json
tutorials/go/template/openChannel.template.sh
tutorials/go/template/publishAndStartService.template.sh
tutorials/java/template/daemonConfigFile.template.json
tutorials/java/template/openChannel.template.sh
tutorials/java/template/publishAndStartService.template.sh
tutorials/process/Dockerfile
tutorials/process/index.md
tutorials/publish.md

#87 
Update the document based on the latest commands

rectify  obsolete commands and general clean up based on the now metadata structure and latest snet-cli commands 

---

docs/concepts/rfai.md

#101- RFAI Language change 

---

docs/concepts/organization-metadata.md

Correct the structure of the Org metadata

#103 synch with the latest Organization metadata structure

---

_data/navigation.yml

Quick fix on the link for channel storage

Quick fix on the link for channel storage

---

theme/_layouts/homepage.html

Removing the blog section

---

tutorials/publish.md

Pair PR for https://github.com/singnet/snet-daemon/pull/415 and https://github.com/singnet/snet-daemon/issues/398

Fix typos in channel configs

---

tutorials/cpp/index.md
tutorials/cpp/template/publishAndStartService.template.sh
tutorials/go/index.md
tutorials/go/template/publishAndStartService.template.sh
tutorials/java/index.md
tutorials/java/template/publishAndStartService.template.sh
tutorials/process/index.md
tutorials/python/index.md
tutorials/python/template/publishAndStartService.template.sh

Creating the user's organization only if it doesn't exist.

Checking if the organization already exists before creating.

---

docs/ai-developers/troubleshooting.md

Adding a step-by-step tutorial about how to get rid of the `RESOURCE_EXHAUSTED` gRPC error code.

[troubleshooting] Adding gRPC message size fix.

---

theme/_includes/google-analytics.html

Checking out google analytics tag

Checking out google analytics tag

---

theme/_includes/google-analytics.html

Google analytics bug testing

---

theme/_includes/site-header.html
theme/_sass/_v3.scss
theme/assets/images/banner/announcement.svg
theme/assets/images/banner/close.svg

New banner

---

products/index.md
products/rfai.md
theme/_includes/site-header.html
theme/_layouts/overview.html

Various RFAI Sunsetting changes. Also removing the Hardfork banner from top.

Rfai sunset

---

products/rfai.md

Removing the RFAI Sunsetting text from Products/RFAI Page

Removing the RFAI Sunsetting text from Products/RFAI Page

---

docs/ai-consumers/sdk-tutorial.md

sdk-tutorial.md

---

_data/navigation.yml
docs/ai-consumers/java-sdk-first-steps.md
docs/ai-consumers/nodejs-sdk-first-steps.md
docs/ai-consumers/python-sdk-calculator-example.md
docs/ai-consumers/python-sdk-console-app-example.md
docs/ai-consumers/python-sdk-documentation.md
docs/ai-consumers/python-sdk-first-steps.md
docs/ai-consumers/python-sdk-tech-docs/account.md
docs/ai-consumers/sdk.md

First step to update and expand python SDK documentation.

Expanding python sdk documentation

---

_data/navigation.yml
docs/ai-consumers/python-sdk/calculator-example.md
docs/ai-consumers/python-sdk/console-app-example.md
docs/ai-consumers/python-sdk/docs/account.md
docs/ai-consumers/python-sdk/docs/client_lib_generator.md
docs/ai-consumers/python-sdk/docs/concurrency_manager.md
docs/ai-consumers/python-sdk/docs/config.md
docs/ai-consumers/python-sdk/docs/init.md
docs/ai-consumers/python-sdk/docs/service_client.md
docs/ai-consumers/python-sdk/documentation.md
docs/ai-consumers/python-sdk/first-steps.md
docs/ai-consumers/sdk.md

New section "Python SDK" with serveral sub-sections: first-steps, documentation, and examples.

New section "Python SDK" with serveral sub-sections.

---

_data/navigation.yml
docs/ai-consumers/sdk.md

Fixes with navigation panel

---

_data/navigation.yml
docs/python-sdk/doc_files/index.md

Reworked access to python SDK technical documentation files

Reworked access to python SDK technical documentation files

---

_data/navigation.yml
docs/ai-developers/filecoin.md

Added doc for FileCoin usage "FileCoin Storage Provider" in section AI Developers → Setup Guide.

FileCoin Storage Provider
